# Trigger on branches
trigger:
- main

# Python versions to test
pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python3:
      python.version: '{{ cookiecutter.python_version }}'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

# Install build dependencies.
- script: |
    python -m pip install --upgrade pip setuptools
  displayName: 'Installing build packages'

# Install the project package.
- script: |
    python -m pip install -e .[dev]
  displayName: 'Installing project package'

# Run pip-audit to scan for vulnerabilities in working environment.
- script: |
    python -m pip install pip-audit
    python -m pip_audit --skip-editable
  displayName: "Checking vulnerabilities with pip-audit."
  # Only warn about vulnerabilities.
  continueOnError: true

# Run isort on src.
- script: |
    python -m pip install isort
    python -m isort -c -rc src/
  displayName: 'Sorting imports with isort'

# Run auto-formatter on src.
- script: |
    python -m pip install black
    python -m black --check src/
  displayName: 'Running autoformatter black'

# Run linting on src
- script: |
    python -m pip install pylint
    python -m pylint src/
  displayName: 'Running linting with pylint'

# Run unit tests and compute test coverage
- script: |
    python -m pip install pytest pytest-cov pytest-azurepipelines
    python -m pytest --ignore=docs/ --cov=src/ --cov-report=xml tests/
  displayName: 'Running tests with pytest'

# Format and publish coverage report
- task: PublishCodeCoverageResults@1
  displayName: 'Publish Cobertura Coverage Report'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '**/coverage.xml'
    failIfCoverageEmpty: false