# Trigger on branches
trigger:
- main

# Python versions to test
pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python39:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

# Install build dependencies.
- script: |
    python -m pip install --upgrade pip setuptools
  displayName: 'Installing build packages'

# Install the project package.
- script: |
    python -m pip install -e .[dev]
  displayName: 'Installing project package'

# Run isort on src.
- script: |
    python -m pip install isort
    python -m isort -c -rc src/
  displayName: 'Sorting imports with isort'
  enabled: true
  continueOnError: false

# Run auto-formatter on src.
- script: |
    python -m pip install black
    python -m black --check src/
  displayName: 'Running autoformatter black'
  enabled: true
  continueOnError: false

# Run linting on src
- script: |
    python -m pip install pylint
    python -m pylint src/
  displayName: 'Running linting with pylint'
  enabled: true
  continueOnError: false

# Run unit tests and compute test coverage
- script: |
    python -m pip install pytest pytest-cov pytest-azurepipelines
    python -m pytest --ignore=docs/ --cov=src/ --cov-report=xml tests/
  displayName: 'Running tests with pytest'
  enabled: true
  continueOnError: false

# Format and publish coverage report
- task: PublishCodeCoverageResults@1
  displayName: 'Publish Cobertura Coverage Report'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '**/coverage.xml'
    failIfCoverageEmpty: false